sudo: required

services:
  - docker

before_install:
  - docker build -t test-client -f ./client/Dockerfile.dev ./client

script: skip

after_success:
  - docker build -t client -f ./client/Dockerfile.dev ./client
  - docker build -t admin -f ./client/Dockerfile.dev ./admin
  - docker build -t db -f ./client/Dockerfile.dev ./db
  - docker build -t proxy -f ./client/Dockerfile.dev ./proxy
