version: '3.5'
services:

  db:
    build:
      dockerfile: Dockerfile.dev
      context: ./db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
    depends_on:
      - db

  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client


  admin:
    build:
      dockerfile: Dockerfile.dev
      context: ./admin
#    volumes:
#      - /app/node_modules
#      - ./admin:/app

  proxy:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./proxy
    ports:
      - '80:80'
    depends_on:
      - "db"
      - "client"
      - "admin"
